#!/usr/bin/env python3
"""export_rules.py OUTPUT [--ste] [--tropes=PATH ...] [--force]

Write the writing rules and the AI trope catalog to OUTPUT as one Markdown
file for Claude Code to load at the start of every session. `/ai-slop:init`
runs it and writes to `~/.claude/rules/` by default, a directory that Claude
Code reads at launch for every project. The file opens with an instruction to
apply the rules to the text that the model writes, including its replies in
chat, so its wording addresses the model, where WRITING.md from
`/ai-slop:writing` addresses the contributors of one project.

The file holds the layers that apply to any prose: the general layer, and the
STE layer with `--ste`. The scientific and LaTeX layers stay out, since they
apply to research articles and LaTeX source, and `/ai-slop:writing` writes
them into the WRITING.md of a paper project. Each layer goes under its own H2
heading with a sentence that states where it applies, and its headings move one
level down. A layer's H1 title and its intro paragraph, which describe the file
and the skills that load it, are left out. So is its self-check section, which
restates the layer's rules item by item. The file's opening paragraph asks for
the check instead, and the rules carry every test and threshold. Leaving the
section out keeps the file small, since every session loads all of it.

The catalog comes from fetch_tropes.py, the only source. When fetching the
catalog fails, the script writes nothing and exits 1. `--tropes=PATH`
(repeatable) reads local files instead, concatenated in the order given, as in
the review skills. The catalog loses its title and preamble (everything before
the first `## ` heading), and its headings move one level down. Each entry
loses the line with its status and category, the `**Avoid patterns like:**`
label before its examples, and the `---` line after it. None of them is an
instruction, and the sentence that introduces the catalog says that each entry
lists examples. A blank line separates an entry's description from its list.

An existing OUTPUT is replaced when it is an earlier export, which the
generation sentence in its header marks. The sentence of an export from
`/ai-slop:export`, the name of the mode up to 2026-09_rev33, counts too. Any
other file at OUTPUT stays, and the script exits 3 unless `--force` is passed.

A one-line summary goes to stderr: whether OUTPUT was created or replaced, the
layers, the catalog's content hash, and the size of the file in bytes and
approximate tokens (bytes / 4), since the whole file stays in context for
every session that loads it.

Exit codes
----------
  0  OUTPUT written.
  1  no catalog: the fetch failed, or a --tropes file has no `## ` heading.
  2  usage error, or a --tropes file or a rule layer could not be read.
  3  OUTPUT exists and was not written by /ai-slop:init, and --force was not
     passed.
"""
import datetime
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
PLUGIN_ROOT = HERE.parent
SHARED = PLUGIN_ROOT / 'shared'
PLUGIN_JSON = PLUGIN_ROOT / '.claude-plugin' / 'plugin.json'

# (flag, file, heading, where the layer applies), in the order the layers stack.
LAYERS = (
    (None, 'rules-general.md', 'General rules',
     'These rules apply to all prose.'),
    ('ste', 'rules-ste.md', 'Simplified Technical English rules',
     'These rules apply to all prose, on top of the general rules.'),
)

FENCE_RE = re.compile(r'^\s*(`{3,}|~{3,})')
HEADING_RE = re.compile(r'^(#{1,5}) ')
AVOID_LINE = '**Avoid patterns like:**'
# An entry's status and category, as in "`consistent` · Sentence Structure".
STATUS_RE = re.compile(r'^`[a-z-]+` · \S')
THEMATIC_BREAK_RE = re.compile(r'^ {0,3}([-*_])( *\1){2,} *$')
SELF_CHECK_RE = re.compile(r'^## Self-check\b', re.I)
EXPORT_MARK = 'This file was generated by `/ai-slop:init`'
# The mark of an export from `/ai-slop:export`, the mode's name up to 2026-09_rev33.
OLD_EXPORT_MARKS = ('This file was generated by `/ai-slop:export`',)


def usage():
    print(__doc__.splitlines()[0].replace('export_rules.py', 'usage: export_rules.py', 1),
          file=sys.stderr)
    return 2


def parse_args(argv):
    """Return (output, flags, tropes, force), or None on a usage error."""
    output, flags, tropes, force = None, set(), [], False
    for arg in argv[1:]:
        if arg == '--ste':
            flags.add('ste')
        elif arg == '--force':
            force = True
        elif arg.startswith('--tropes='):
            path = arg[len('--tropes='):]
            if not path:
                return None
            tropes.append(path)
        elif arg.startswith('-') or output is not None:
            return None
        else:
            output = arg
    if output is None:
        return None
    return output, flags, tropes, force


def from_first_h2(text):
    """The text from its first `## ` heading onward, or '' when it has none."""
    match = re.search(r'^## ', text, re.M)
    return text[match.start():] if match else ''


def demote_headings(text):
    """Move every ATX heading outside a fenced block one level down."""
    out, fence = [], None
    for line in text.splitlines():
        match = FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker[0] * len(marker)
            elif marker.startswith(fence):
                fence = None
        elif fence is None and HEADING_RE.match(line):
            line = '#' + line
        out.append(line)
    return '\n'.join(out)


def drop_self_checks(text):
    """Remove every `## Self-check ...` section, from its heading to the next
    `## ` heading, outside fenced blocks."""
    out, fence, skipping = [], None, False
    for line in text.splitlines():
        match = FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker[0] * len(marker)
            elif marker.startswith(fence):
                fence = None
        elif fence is None and line.startswith('## '):
            skipping = bool(SELF_CHECK_RE.match(line))
        if not skipping:
            out.append(line)
    return '\n'.join(out)


def strip_catalog_markup(text):
    """Drop each entry's status line, `**Avoid patterns like:**` label, and
    thematic break, keep one blank line between an entry's description and its
    list, and collapse the blank lines that the removals leave."""
    out, fence = [], None
    for line in text.splitlines():
        match = FENCE_RE.match(line)
        if match:
            marker = match.group(1)
            if fence is None:
                fence = marker[0] * len(marker)
            elif marker.startswith(fence):
                fence = None
        elif fence is None:
            if (STATUS_RE.match(line) or line.strip() == AVOID_LINE
                    or THEMATIC_BREAK_RE.match(line)):
                if out and out[-1].strip():
                    out.append('')
                continue
            if not line.strip() and out and not out[-1].strip():
                continue
        out.append(line)
    return '\n'.join(out)


def normalize_catalog(text):
    body = from_first_h2(text)
    if not body:
        return ''
    return strip_catalog_markup(demote_headings(body)).strip()


def load_catalog(paths):
    """Return (catalog text, source label), or (None, message) on failure.
    A failure to read a --tropes file raises OSError."""
    if paths:
        text = ''.join(Path(p).read_text(encoding='utf-8') for p in paths)
        return text, ', '.join(paths)
    sys.path.insert(0, str(HERE))
    import fetch_tropes
    text = fetch_tropes.extract_markdown(fetch_tropes.try_fetch(fetch_tropes.VIEWER_URL))
    if not text:
        return None, (f"no catalog from {fetch_tropes.VIEWER_URL}; pass "
                      "--tropes=<path> to use a local copy")
    return text, fetch_tropes.VIEWER_URL


def is_export(path):
    """True when the file at path is an earlier export of this script."""
    try:
        text = path.read_text(encoding='utf-8')
    except (OSError, UnicodeDecodeError):
        return False
    return any(mark in text for mark in (EXPORT_MARK,) + OLD_EXPORT_MARKS)


def skill_version():
    try:
        return json.loads(PLUGIN_JSON.read_text(encoding='utf-8'))['version']
    except (OSError, ValueError, KeyError):
        return 'unknown'


def build(layers, catalog, catalog_hash, today, version):
    """Assemble the exported file from (heading, scope, body) layer triples and
    the normalized catalog."""
    parts = [
        '# Writing rules',
        'Apply these rules to all prose that you write: replies in chat, files '
        'that you create or edit, code comments and docstrings, and commit '
        'messages. They cover the text that you write or change, not existing '
        'text that the task leaves alone. Code, identifiers, and quoted '
        'material stay as written. Where the writing conventions of a project '
        'differ, the project\'s conventions apply. Check each text against '
        'every rule below before you present it.',
        f'{EXPORT_MARK} on {today} from the '
        '[ai-slop-skill](https://github.com/se-uhd/ai-slop-skill) '
        f'(skill version {version}). It combines the writing rules maintained '
        'by the [Software Engineering Group at Heidelberg University]'
        '(https://github.com/se-uhd) with the AI trope catalog from '
        '[tropes.fyi](https://tropes.fyi) by [ossama.is](https://ossama.is). '
        'Running `/ai-slop:init` again replaces this file with the current '
        'rules and catalog, so keep your own additions in a separate file.',
    ]
    for heading, scope, body in layers:
        parts += [f'## {heading}', scope, demote_headings(body).strip()]
    parts += [
        '## AI writing tropes to avoid',
        'The catalog below is from [tropes.fyi](https://tropes.fyi) by '
        f'[ossama.is](https://ossama.is), as fetched on {today} (sha256 '
        f'{catalog_hash}). Each entry describes a pattern and lists examples '
        'of it. Where the catalog and a rule above disagree, the rule above '
        'applies.',
        catalog,
    ]
    return '\n\n'.join(parts) + '\n'


def main(argv):
    parsed = parse_args(argv)
    if parsed is None:
        return usage()
    output, flags, trope_paths, force = parsed
    out_path = Path(output).expanduser()
    existed = out_path.exists()
    if existed and not force and not is_export(out_path):
        print(f"error: {output} exists and was not written by /ai-slop:init; pass "
              "--force to replace it", file=sys.stderr)
        return 3

    layers, names = [], []
    for flag, name, heading, scope in LAYERS:
        if flag is not None and flag not in flags:
            continue
        try:
            text = (SHARED / name).read_text(encoding='utf-8')
        except OSError as exc:
            print(f"error: cannot read rule layer {name}: {exc}", file=sys.stderr)
            return 2
        layers.append((heading, scope, drop_self_checks(from_first_h2(text))))
        names.append(name)

    try:
        raw, source = load_catalog(trope_paths)
    except OSError as exc:
        print(f"error: cannot read --tropes file: {exc}", file=sys.stderr)
        return 2
    if raw is None:
        print(f"error: {source}", file=sys.stderr)
        return 1
    catalog = normalize_catalog(raw)
    if not catalog:
        print(f"error: the catalog from {source} has no `## ` trope heading",
              file=sys.stderr)
        return 1

    catalog_hash = hashlib.sha256(raw.encode('utf-8')).hexdigest()[:12]
    today = datetime.date.today().isoformat()
    content = build(layers, catalog, catalog_hash, today, skill_version())
    try:
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(content, encoding='utf-8')
    except OSError as exc:
        print(f"error: cannot write {output}: {exc}", file=sys.stderr)
        return 2
    size = len(content.encode('utf-8'))
    print(f"{'replaced' if existed else 'created'} {out_path}: {', '.join(names)} "
          f"+ catalog sha256 {catalog_hash}; {size} bytes, about {size // 4} tokens",
          file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
