#!/usr/bin/env python3
"""scan_repo.py [REPO_ROOT] [--commits=<N|all|RANGE>] [--no-commits]

Extract the natural-language text from a whole code repository so the ai-slop
review can scan prose that lives outside a single document or a diff: Markdown and
plain-text files in full, the comments and doc-comments of source and config
files, and the repository's commit messages. This drives `/ai-slop:review-repo`,
the repo-wide counterpart to `/ai-slop:review` (one document) and
`/ai-slop:review-diff` (changed lines only).

REPO_ROOT is a directory and defaults to the current working directory.

Output (stdout): one natural-language line per output line, in grep form

    <relpath>:<line>:<text>

where <relpath> is relative to REPO_ROOT, <line> is 1-based, and <text> is the
prose with its comment markers stripped. Lines are grouped by file and files are
emitted in sorted order, so the output is stable across runs. Commit messages
follow the files, newest first, under a `commit <short-sha>` pseudo-path (no real
file is named that) so the reviewer can group and locate findings by commit. A
one-line summary is printed to stderr (files scanned, how many were prose vs
comment-bearing, how many commit messages, and how many text lines were emitted).

Options:
    --commits=<spec>  Which commit messages to scan. <spec> is a count (the most
                      recent N commits, the default is the most recent 200), the
                      word `all` (the full reachable history), or a git revision
                      range such as `main..HEAD` (the commits on a branch). Merge
                      commits and the standard trailer lines (Co-authored-by,
                      Signed-off-by, ...) are skipped either way.
    --no-commits      Do not scan commit messages at all.

Exit codes:
    0  scanned successfully (even if nothing matched)
    2  REPO_ROOT does not exist or is not a directory

What is scanned:
    File list. In a git repository the file set comes from `git ls-files` at
    REPO_ROOT, so `.gitignore`d build output, dependencies, and untracked files
    are excluded automatically. Outside a git repository the tree is walked with a
    denylist of common build/dependency directories.

    Prose files (reviewed in full): .md .markdown .mdx .txt .text .rst .adoc
    .asciidoc .org .tex. Every non-blank line is emitted, so a LaTeX file's `%`
    comments are reviewed alongside its body (just as comments are in source
    files). Fenced code blocks inside Markdown are skipped (they are code, not
    prose); blank lines are skipped.

    Comment-bearing files (only the comments are reviewed): source and config
    files whose extension or name maps to a comment syntax (see COMMENT_SPECS /
    NAME_SPECS). Both line comments (`//`, `#`, `--`, `;`) and block comments
    (`/* */`, `<!-- -->`, Python `\"\"\" \"\"\"`/`''' '''`) are extracted; a
    leading decoration run (`*`, `/`, `!`) on a continuation line is stripped.

    Skipped: binary/asset extensions, lockfiles, source maps, files above a size
    cap, and files whose head carries a generated-file marker ("DO NOT EDIT",
    "@generated", "Code generated by", ...), since fixing prose in generated output
    is futile.

    Commit messages (unless --no-commits): the subject and body of each selected
    commit, from `git log` (so this applies only in a git work tree). The standard
    trailer lines (Co-authored-by, Signed-off-by, Reviewed-by, ...) and merge
    commits are skipped, since neither is hand-written prose. Note that published
    commit history is immutable; findings here are mostly advisory (a guide for
    future messages, or for rewording a branch's commits before they are pushed)
    rather than something `/ai-slop:revise` can apply.

Known limitations (this is a heuristic extractor, not a lexer for every language):
    - Comment-opener detection is string-aware for the common quote characters
      (" ' `) so a `//` or `#` inside a string literal is not mistaken for a
      comment, but it does not model every language's string rules (heredocs, raw
      strings, regex literals). A stray false positive is harmless noise the
      reviewer ignores; a missed comment is a missed finding.
    - At most the first comment opener on a line plus any block continuation is
      captured; a second, trailing comment on the same physical line is rare and
      not extracted.
    - LaTeX (`.tex`) is reviewed as prose (its body and `%` comments, with markup
      the reviewer ignores) against the general rules only. The dedicated
      `/ai-slop:review` LaTeX layer remains the tool for citations, BibTeX, and
      section-aware checks; repo mode does not load it.
"""
import os
import re
import subprocess
import sys
from pathlib import Path

# Per-language comment syntax: (line_markers, block_pairs). A block pair is
# (open, close). Order within line_markers/block_openers does not matter; the
# scanner picks the earliest match on the line.
HASH = (('#',), ())
SLASH = (('//',), (('/*', '*/'),))
SLASH_HASH = (('//', '#'), (('/*', '*/'),))
BLOCK_ONLY = ((), (('/*', '*/'),))
HTML = ((), (('<!--', '-->'),))
SQL = (('--',), (('/*', '*/'),))
LUA = (('--',), (('--[[', ']]'),))
SEMI = ((';',), ())
PY = (('#',), (('"""', '"""'), ("'''", "'''")))

# Extension (lowercased, no dot) -> comment spec.
COMMENT_SPECS = {
    # hash-comment scripts and config
    'py': PY, 'pyi': PY, 'rb': HASH, 'sh': HASH, 'bash': HASH, 'zsh': HASH,
    'fish': HASH, 'ps1': HASH, 'yaml': HASH, 'yml': HASH, 'toml': HASH,
    'ini': HASH, 'cfg': HASH, 'conf': HASH, 'properties': HASH, 'env': HASH,
    'r': HASH, 'pl': HASH, 'pm': HASH, 'tf': HASH, 'tfvars': HASH, 'mk': HASH,
    'cmake': HASH, 'dockerfile': HASH, 'gitignore': HASH, 'gitattributes': HASH,
    'editorconfig': HASH,
    # slash-comment source
    'java': SLASH, 'kt': SLASH, 'kts': SLASH, 'groovy': SLASH, 'gradle': SLASH,
    'js': SLASH, 'mjs': SLASH, 'cjs': SLASH, 'jsx': SLASH, 'ts': SLASH,
    'tsx': SLASH, 'c': SLASH, 'h': SLASH, 'cc': SLASH, 'cpp': SLASH, 'cxx': SLASH,
    'hpp': SLASH, 'cs': SLASH, 'go': SLASH, 'rs': SLASH, 'swift': SLASH,
    'scala': SLASH, 'dart': SLASH, 'json5': SLASH, 'jsonc': SLASH,
    'scss': SLASH, 'less': SLASH, 'css': BLOCK_ONLY, 'php': SLASH_HASH,
    # markup (block only)
    'html': HTML, 'htm': HTML, 'xml': HTML, 'xhtml': HTML, 'vue': HTML,
    'svelte': HTML,
    # other line-comment families
    'sql': SQL, 'lua': LUA, 'el': SEMI, 'lisp': SEMI, 'clj': SEMI, 'cljs': SEMI,
}

# Files with no informative extension, matched on the full basename.
NAME_SPECS = {
    'Dockerfile': HASH, 'Makefile': HASH, 'makefile': HASH, 'CMakeLists.txt': HASH,
    '.gitignore': HASH, '.gitattributes': HASH, '.editorconfig': HASH,
    '.dockerignore': HASH, '.npmignore': HASH, '.env': HASH,
}

PROSE_EXTS = {'md', 'markdown', 'mdx', 'txt', 'text', 'rst', 'adoc', 'asciidoc', 'org', 'tex'}

# Lockfiles and other tracked-but-not-prose files, matched on the basename.
SKIP_NAMES = {
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'composer.lock',
    'Cargo.lock', 'poetry.lock', 'Gemfile.lock', 'go.sum', 'gradle.lockfile',
}

# Directories skipped when walking a non-git tree (a git repo uses `git ls-files`,
# which already honors .gitignore).
DENY_DIRS = {
    '.git', 'node_modules', 'build', 'dist', 'out', 'target', '.gradle', '.idea',
    '.vscode', 'vendor', '__pycache__', '.venv', 'venv', '.next', '.angular',
    '.nuxt', 'coverage', 'bin', 'obj', '_vendor', '.mypy_cache', '.pytest_cache',
}

MAX_BYTES = 1_000_000  # skip a file larger than this (generated/vendored blobs)
DEFAULT_COMMIT_LIMIT = 200  # most recent N commits scanned when --commits is unset
# Standard git trailer lines: metadata, not hand-written prose, so not reviewed.
TRAILER_RE = re.compile(
    r'^(?:Co-authored-by|Signed-off-by|Reviewed-by|Acked-by|Tested-by|'
    r'Reported-by|Suggested-by|Reviewed-on|Change-Id|Cc|Fixes|Closes|Refs|'
    r'Link|See-also):',
    re.IGNORECASE,
)
GENERATED_RE = re.compile(
    r'do not edit|@generated|auto-?generated|code generated by|generated by',
    re.IGNORECASE,
)
QUOTE_CHARS = ('"', "'", '`')
DECORATION_RE = re.compile(r'^[*/!]+\s?')  # leading ` * `, `///`, `//!` decoration


def in_denylisted_dir(relpath):
    """True if any parent directory of relpath is denylisted (a vendored or build
    directory). Applied to the git file list too, so committed third-party code
    (e.g. a tracked `vendor/` or `_vendor/`) is not reviewed as the repo's prose."""
    return any(part in DENY_DIRS for part in Path(relpath).parts[:-1])


def list_files(root):
    """Return (relpath, abspath) pairs for the files to consider. Prefers
    `git ls-files` (tracked files, .gitignore honored); falls back to an os.walk
    with DENY_DIRS pruned when root is not a git working tree. Denylisted
    directories are excluded in both modes."""
    try:
        res = subprocess.run(
            ['git', '-C', str(root), 'ls-files', '-z'],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        res = None
    if res is not None and res.returncode == 0:
        rels = [p for p in res.stdout.split('\0') if p and not in_denylisted_dir(p)]
        return [(r, str(Path(root) / r)) for r in rels]
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in DENY_DIRS]
        for name in filenames:
            ab = Path(dirpath) / name
            out.append((str(ab.relative_to(root)), str(ab)))
    return out


def classify(relpath):
    """Return ('prose'|'comment'|'skip', spec_or_None) for a path."""
    name = os.path.basename(relpath)
    if name in SKIP_NAMES:
        return ('skip', None)
    if name in NAME_SPECS:
        return ('comment', NAME_SPECS[name])
    ext = name.rsplit('.', 1)[-1].lower() if '.' in name else ''
    if ext in PROSE_EXTS:
        return ('prose', None)
    if ext in COMMENT_SPECS:
        return ('comment', COMMENT_SPECS[ext])
    return ('skip', None)


def looks_generated(text):
    """True if the file head carries a generated-file marker."""
    return GENERATED_RE.search(text[:2000]) is not None


def find_opener(line, start, line_markers, block_openers):
    """Scan line from `start` for the earliest comment opener that lies outside a
    string literal. Returns (index, 'line'|'block', marker) or None. String-aware
    for the common quote characters; a block opener (e.g. Python `\"\"\"`) is
    tested before the quote-state update so a triple-quote is not swallowed as a
    one-character string."""
    i, n, quote = start, len(line), None
    while i < n:
        c = line[i]
        if quote is not None:
            if c == '\\':
                i += 2
                continue
            if c == quote:
                quote = None
            i += 1
            continue
        for m in block_openers:
            if line.startswith(m, i):
                return (i, 'block', m)
        for m in line_markers:
            if line.startswith(m, i):
                return (i, 'line', m)
        if c in QUOTE_CHARS:
            quote = c
        i += 1
    return None


def clean(text):
    """Strip whitespace and a leading comment-decoration run from comment text."""
    return DECORATION_RE.sub('', text.strip()).strip()


def extract_comments(text, spec):
    """Yield (lineno, cleaned_text) for the comment content of a source/config
    file. `spec` is (line_markers, block_pairs)."""
    line_markers, block_pairs = spec
    block_openers = [op for op, _ in block_pairs]
    close_for = {op: cl for op, cl in block_pairs}
    in_block_close = None
    for lineno, raw in enumerate(text.split('\n'), 1):
        line = raw.rstrip('\r')
        if lineno == 1 and line.startswith('#!'):
            continue  # a shebang is an interpreter directive, not prose
        pos = 0
        while True:
            if in_block_close is not None:
                ci = line.find(in_block_close, pos)
                if ci == -1:
                    yield lineno, clean(line[pos:])
                    break
                yield lineno, clean(line[pos:ci])
                pos = ci + len(in_block_close)
                in_block_close = None
                continue
            ev = find_opener(line, pos, line_markers, block_openers)
            if ev is None:
                break
            idx, kind, marker = ev
            if kind == 'line':
                yield lineno, clean(line[idx + len(marker):])
                break
            in_block_close = close_for[marker]
            pos = idx + len(marker)


FENCE_RE = re.compile(r'^\s*(```|~~~)')


def extract_prose(text, is_markdown):
    """Yield (lineno, line) for the non-blank lines of a prose file, skipping
    fenced code blocks in Markdown."""
    in_fence = False
    for lineno, raw in enumerate(text.split('\n'), 1):
        line = raw.rstrip('\r')
        if is_markdown and FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if line.strip():
            yield lineno, line.rstrip()


def read_text(abspath):
    """Read a file as UTF-8 text, or return None if it is too large, binary, or
    unreadable."""
    try:
        if os.path.getsize(abspath) > MAX_BYTES:
            return None
        with open(abspath, 'rb') as fh:
            data = fh.read()
    except OSError:
        return None
    if b'\x00' in data:
        return None
    try:
        return data.decode('utf-8')
    except UnicodeDecodeError:
        return None


def commit_selector(spec):
    """Translate a --commits spec into the `git log` selector arguments. A count
    (int or all-digit string) becomes `-n N`, `all` selects the full history (no
    limiter), and anything else is passed through as a revision range argument
    (e.g. `main..HEAD`)."""
    if isinstance(spec, int):
        return ['-n', str(spec)]
    if spec == 'all':
        return []
    if spec.isdigit():
        return ['-n', spec]
    return [spec]


def list_commits(root, spec):
    """Return [(short_sha, message)] for the selected commits, newest first.
    Returns [] when commit scanning is off (spec is None), when root is not a git
    work tree or git is unavailable, or when there are no commits. Merge commits
    are excluded."""
    if spec is None:
        return []
    cmd = (['git', '-C', str(root), 'log', '--no-merges', '-z', '--format=%H%n%B']
           + commit_selector(spec))
    try:
        res = subprocess.run(cmd, capture_output=True, text=True)
    except FileNotFoundError:
        return []
    if res.returncode != 0:
        return []
    out = []
    for record in res.stdout.split('\0'):
        record = record.strip('\n')
        if not record:
            continue
        sha, _, body = record.partition('\n')
        out.append((sha[:9], body))
    return out


def extract_commit_message(message):
    """Yield (lineno, line) for the non-blank, non-trailer lines of a commit
    message. Line 1 is the subject; trailer lines (Co-authored-by, ...) are
    dropped because they are metadata, not prose."""
    for lineno, raw in enumerate(message.split('\n'), 1):
        line = raw.rstrip('\r').rstrip()
        if line.strip() and not TRAILER_RE.match(line):
            yield lineno, line


def scan(root, commit_spec=DEFAULT_COMMIT_LIMIT):
    """Scan the repo and return (lines, n_files, n_prose, n_comment, n_commits).
    Each line is a formatted `relpath:lineno:text` string; commit messages use a
    `commit <short-sha>` pseudo-path and follow the files, newest first."""
    lines = []
    n_files = n_prose = n_comment = 0
    for relpath, abspath in sorted(list_files(root)):
        kind, spec = classify(relpath)
        if kind == 'skip':
            continue
        text = read_text(abspath)
        if text is None or looks_generated(text):
            continue
        ext = relpath.rsplit('.', 1)[-1].lower() if '.' in relpath else ''
        if kind == 'prose':
            pairs = extract_prose(text, ext in ('md', 'markdown', 'mdx'))
        else:
            pairs = extract_comments(text, spec)
        emitted = [(ln, t) for ln, t in pairs if t]
        if not emitted:
            continue
        n_files += 1
        n_prose += kind == 'prose'
        n_comment += kind == 'comment'
        for ln, t in emitted:
            lines.append(f'{relpath}:{ln}:{t}')
    n_commits = 0
    for sha, message in list_commits(root, commit_spec):
        emitted = [(ln, t) for ln, t in extract_commit_message(message) if t]
        if not emitted:
            continue
        n_commits += 1
        for ln, t in emitted:
            lines.append(f'commit {sha}:{ln}:{t}')
    return lines, n_files, n_prose, n_comment, n_commits


def parse_args(argv):
    """Parse argv into (root, commit_spec). The first bare argument is the repo
    root; --commits=<spec> and --no-commits control commit scanning. A bad
    --commits value or an extra positional argument returns None to signal an
    error; other --flags are left to the skill layer and ignored here."""
    root, commit_spec = None, DEFAULT_COMMIT_LIMIT
    for arg in argv[1:]:
        if arg == '--no-commits':
            commit_spec = None
        elif arg.startswith('--commits='):
            val = arg.split('=', 1)[1]
            commit_spec = int(val) if val.isdigit() else val
            if commit_spec == '':
                return None
        elif arg.startswith('--'):
            continue  # a skill-layer flag (e.g. --scientific); not ours
        elif root is None:
            root = Path(arg)
        else:
            return None
    return (root or Path('.'), commit_spec)


def main(argv):
    parsed = parse_args(argv)
    if parsed is None:
        print("scan_repo: usage: scan_repo.py [REPO_ROOT] "
              "[--commits=<N|all|RANGE>] [--no-commits]", file=sys.stderr)
        return 2
    root, commit_spec = parsed
    if not root.is_dir():
        print(f"scan_repo: not a directory: {root}", file=sys.stderr)
        return 2
    lines, n_files, n_prose, n_comment, n_commits = scan(root, commit_spec)
    sys.stdout.write('\n'.join(lines))
    if lines:
        sys.stdout.write('\n')
    print(
        f"scanned {n_files} file(s) with text "
        f"({n_prose} prose, {n_comment} with comments) "
        f"and {n_commits} commit message(s); {len(lines)} line(s).",
        file=sys.stderr,
    )
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
