#!/usr/bin/env python3
"""scan_repo.py [REPO_ROOT]

Extract the natural-language text from a whole code repository so the ai-slop
review can scan prose that lives outside a single document or a diff: Markdown and
plain-text files in full, plus the comments and doc-comments of source and config
files. This drives `/ai-slop:review-repo`, the repo-wide counterpart to
`/ai-slop:review` (one document) and `/ai-slop:review-diff` (changed lines only).

REPO_ROOT is a directory and defaults to the current working directory.

Output (stdout): one natural-language line per output line, in grep form

    <relpath>:<line>:<text>

where <relpath> is relative to REPO_ROOT, <line> is 1-based, and <text> is the
prose with its comment markers stripped. Lines are grouped by file and files are
emitted in sorted order, so the output is stable across runs. A one-line summary
is printed to stderr (files scanned, how many were prose vs comment-bearing, and
how many text lines were emitted).

Exit codes:
    0  scanned successfully (even if nothing matched)
    2  REPO_ROOT does not exist or is not a directory

What is scanned:
    File list. In a git repository the file set comes from `git ls-files` at
    REPO_ROOT, so `.gitignore`d build output, dependencies, and untracked files
    are excluded automatically. Outside a git repository the tree is walked with a
    denylist of common build/dependency directories.

    Prose files (reviewed in full): .md .markdown .mdx .txt .text .rst .adoc
    .asciidoc .org. Fenced code blocks inside Markdown are skipped (they are code,
    not prose); blank lines are skipped.

    Comment-bearing files (only the comments are reviewed): source and config
    files whose extension or name maps to a comment syntax (see COMMENT_SPECS /
    NAME_SPECS). Both line comments (`//`, `#`, `--`, `;`) and block comments
    (`/* */`, `<!-- -->`, Python `\"\"\" \"\"\"`/`''' '''`) are extracted; a
    leading decoration run (`*`, `/`, `!`) on a continuation line is stripped.

    Skipped: binary/asset extensions, lockfiles, source maps, files above a size
    cap, and files whose head carries a generated-file marker ("DO NOT EDIT",
    "@generated", "Code generated by", ...), since fixing prose in generated output
    is futile.

Known limitations (this is a heuristic extractor, not a lexer for every language):
    - Comment-opener detection is string-aware for the common quote characters
      (" ' `) so a `//` or `#` inside a string literal is not mistaken for a
      comment, but it does not model every language's string rules (heredocs, raw
      strings, regex literals). A stray false positive is harmless noise the
      reviewer ignores; a missed comment is a missed finding.
    - At most the first comment opener on a line plus any block continuation is
      captured; a second, trailing comment on the same physical line is rare and
      not extracted.
    - LaTeX (`.tex`) is intentionally not in the comment table: a LaTeX project is
      reviewed by `/ai-slop:review` with the dedicated LaTeX layer, where `%` is a
      source mechanic rather than prose.
"""
import os
import re
import subprocess
import sys
from pathlib import Path

# Per-language comment syntax: (line_markers, block_pairs). A block pair is
# (open, close). Order within line_markers/block_openers does not matter; the
# scanner picks the earliest match on the line.
HASH = (('#',), ())
SLASH = (('//',), (('/*', '*/'),))
SLASH_HASH = (('//', '#'), (('/*', '*/'),))
BLOCK_ONLY = ((), (('/*', '*/'),))
HTML = ((), (('<!--', '-->'),))
SQL = (('--',), (('/*', '*/'),))
LUA = (('--',), (('--[[', ']]'),))
SEMI = ((';',), ())
PY = (('#',), (('"""', '"""'), ("'''", "'''")))

# Extension (lowercased, no dot) -> comment spec.
COMMENT_SPECS = {
    # hash-comment scripts and config
    'py': PY, 'pyi': PY, 'rb': HASH, 'sh': HASH, 'bash': HASH, 'zsh': HASH,
    'fish': HASH, 'ps1': HASH, 'yaml': HASH, 'yml': HASH, 'toml': HASH,
    'ini': HASH, 'cfg': HASH, 'conf': HASH, 'properties': HASH, 'env': HASH,
    'r': HASH, 'pl': HASH, 'pm': HASH, 'tf': HASH, 'tfvars': HASH, 'mk': HASH,
    'cmake': HASH, 'dockerfile': HASH, 'gitignore': HASH, 'gitattributes': HASH,
    'editorconfig': HASH,
    # slash-comment source
    'java': SLASH, 'kt': SLASH, 'kts': SLASH, 'groovy': SLASH, 'gradle': SLASH,
    'js': SLASH, 'mjs': SLASH, 'cjs': SLASH, 'jsx': SLASH, 'ts': SLASH,
    'tsx': SLASH, 'c': SLASH, 'h': SLASH, 'cc': SLASH, 'cpp': SLASH, 'cxx': SLASH,
    'hpp': SLASH, 'cs': SLASH, 'go': SLASH, 'rs': SLASH, 'swift': SLASH,
    'scala': SLASH, 'dart': SLASH, 'json5': SLASH, 'jsonc': SLASH,
    'scss': SLASH, 'less': SLASH, 'css': BLOCK_ONLY, 'php': SLASH_HASH,
    # markup (block only)
    'html': HTML, 'htm': HTML, 'xml': HTML, 'xhtml': HTML, 'vue': HTML,
    'svelte': HTML,
    # other line-comment families
    'sql': SQL, 'lua': LUA, 'el': SEMI, 'lisp': SEMI, 'clj': SEMI, 'cljs': SEMI,
}

# Files with no informative extension, matched on the full basename.
NAME_SPECS = {
    'Dockerfile': HASH, 'Makefile': HASH, 'makefile': HASH, 'CMakeLists.txt': HASH,
    '.gitignore': HASH, '.gitattributes': HASH, '.editorconfig': HASH,
    '.dockerignore': HASH, '.npmignore': HASH, '.env': HASH,
}

PROSE_EXTS = {'md', 'markdown', 'mdx', 'txt', 'text', 'rst', 'adoc', 'asciidoc', 'org'}

# Lockfiles and other tracked-but-not-prose files, matched on the basename.
SKIP_NAMES = {
    'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml', 'composer.lock',
    'Cargo.lock', 'poetry.lock', 'Gemfile.lock', 'go.sum', 'gradle.lockfile',
}

# Directories skipped when walking a non-git tree (a git repo uses `git ls-files`,
# which already honors .gitignore).
DENY_DIRS = {
    '.git', 'node_modules', 'build', 'dist', 'out', 'target', '.gradle', '.idea',
    '.vscode', 'vendor', '__pycache__', '.venv', 'venv', '.next', '.angular',
    '.nuxt', 'coverage', 'bin', 'obj', '_vendor', '.mypy_cache', '.pytest_cache',
}

MAX_BYTES = 1_000_000  # skip a file larger than this (generated/vendored blobs)
GENERATED_RE = re.compile(
    r'do not edit|@generated|auto-?generated|code generated by|generated by',
    re.IGNORECASE,
)
QUOTE_CHARS = ('"', "'", '`')
DECORATION_RE = re.compile(r'^[*/!]+\s?')  # leading ` * `, `///`, `//!` decoration


def in_denylisted_dir(relpath):
    """True if any parent directory of relpath is denylisted (a vendored or build
    directory). Applied to the git file list too, so committed third-party code
    (e.g. a tracked `vendor/` or `_vendor/`) is not reviewed as the repo's prose."""
    return any(part in DENY_DIRS for part in Path(relpath).parts[:-1])


def list_files(root):
    """Return (relpath, abspath) pairs for the files to consider. Prefers
    `git ls-files` (tracked files, .gitignore honored); falls back to an os.walk
    with DENY_DIRS pruned when root is not a git working tree. Denylisted
    directories are excluded in both modes."""
    try:
        res = subprocess.run(
            ['git', '-C', str(root), 'ls-files', '-z'],
            capture_output=True, text=True,
        )
    except FileNotFoundError:
        res = None
    if res is not None and res.returncode == 0:
        rels = [p for p in res.stdout.split('\0') if p and not in_denylisted_dir(p)]
        return [(r, str(Path(root) / r)) for r in rels]
    out = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = [d for d in dirnames if d not in DENY_DIRS]
        for name in filenames:
            ab = Path(dirpath) / name
            out.append((str(ab.relative_to(root)), str(ab)))
    return out


def classify(relpath):
    """Return ('prose'|'comment'|'skip', spec_or_None) for a path."""
    name = os.path.basename(relpath)
    if name in SKIP_NAMES:
        return ('skip', None)
    if name in NAME_SPECS:
        return ('comment', NAME_SPECS[name])
    ext = name.rsplit('.', 1)[-1].lower() if '.' in name else ''
    if ext in PROSE_EXTS:
        return ('prose', None)
    if ext in COMMENT_SPECS:
        return ('comment', COMMENT_SPECS[ext])
    return ('skip', None)


def looks_generated(text):
    """True if the file head carries a generated-file marker."""
    return GENERATED_RE.search(text[:2000]) is not None


def find_opener(line, start, line_markers, block_openers):
    """Scan line from `start` for the earliest comment opener that lies outside a
    string literal. Returns (index, 'line'|'block', marker) or None. String-aware
    for the common quote characters; a block opener (e.g. Python `\"\"\"`) is
    tested before the quote-state update so a triple-quote is not swallowed as a
    one-character string."""
    i, n, quote = start, len(line), None
    while i < n:
        c = line[i]
        if quote is not None:
            if c == '\\':
                i += 2
                continue
            if c == quote:
                quote = None
            i += 1
            continue
        for m in block_openers:
            if line.startswith(m, i):
                return (i, 'block', m)
        for m in line_markers:
            if line.startswith(m, i):
                return (i, 'line', m)
        if c in QUOTE_CHARS:
            quote = c
        i += 1
    return None


def clean(text):
    """Strip whitespace and a leading comment-decoration run from comment text."""
    return DECORATION_RE.sub('', text.strip()).strip()


def extract_comments(text, spec):
    """Yield (lineno, cleaned_text) for the comment content of a source/config
    file. `spec` is (line_markers, block_pairs)."""
    line_markers, block_pairs = spec
    block_openers = [op for op, _ in block_pairs]
    close_for = {op: cl for op, cl in block_pairs}
    in_block_close = None
    for lineno, raw in enumerate(text.split('\n'), 1):
        line = raw.rstrip('\r')
        if lineno == 1 and line.startswith('#!'):
            continue  # a shebang is an interpreter directive, not prose
        pos = 0
        while True:
            if in_block_close is not None:
                ci = line.find(in_block_close, pos)
                if ci == -1:
                    yield lineno, clean(line[pos:])
                    break
                yield lineno, clean(line[pos:ci])
                pos = ci + len(in_block_close)
                in_block_close = None
                continue
            ev = find_opener(line, pos, line_markers, block_openers)
            if ev is None:
                break
            idx, kind, marker = ev
            if kind == 'line':
                yield lineno, clean(line[idx + len(marker):])
                break
            in_block_close = close_for[marker]
            pos = idx + len(marker)


FENCE_RE = re.compile(r'^\s*(```|~~~)')


def extract_prose(text, is_markdown):
    """Yield (lineno, line) for the non-blank lines of a prose file, skipping
    fenced code blocks in Markdown."""
    in_fence = False
    for lineno, raw in enumerate(text.split('\n'), 1):
        line = raw.rstrip('\r')
        if is_markdown and FENCE_RE.match(line):
            in_fence = not in_fence
            continue
        if in_fence:
            continue
        if line.strip():
            yield lineno, line.rstrip()


def read_text(abspath):
    """Read a file as UTF-8 text, or return None if it is too large, binary, or
    unreadable."""
    try:
        if os.path.getsize(abspath) > MAX_BYTES:
            return None
        with open(abspath, 'rb') as fh:
            data = fh.read()
    except OSError:
        return None
    if b'\x00' in data:
        return None
    try:
        return data.decode('utf-8')
    except UnicodeDecodeError:
        return None


def scan(root):
    """Scan the repo and return (lines, n_files, n_prose, n_comment). Each line is
    a formatted `relpath:lineno:text` string."""
    lines = []
    n_files = n_prose = n_comment = 0
    for relpath, abspath in sorted(list_files(root)):
        kind, spec = classify(relpath)
        if kind == 'skip':
            continue
        text = read_text(abspath)
        if text is None or looks_generated(text):
            continue
        ext = relpath.rsplit('.', 1)[-1].lower() if '.' in relpath else ''
        if kind == 'prose':
            pairs = extract_prose(text, ext in ('md', 'markdown', 'mdx'))
        else:
            pairs = extract_comments(text, spec)
        emitted = [(ln, t) for ln, t in pairs if t]
        if not emitted:
            continue
        n_files += 1
        n_prose += kind == 'prose'
        n_comment += kind == 'comment'
        for ln, t in emitted:
            lines.append(f'{relpath}:{ln}:{t}')
    return lines, n_files, n_prose, n_comment


def main(argv):
    root = Path(argv[1]) if len(argv) > 1 else Path('.')
    if not root.is_dir():
        print(f"scan_repo: not a directory: {root}", file=sys.stderr)
        return 2
    lines, n_files, n_prose, n_comment = scan(root)
    sys.stdout.write('\n'.join(lines))
    if lines:
        sys.stdout.write('\n')
    print(
        f"scanned {n_files} file(s) with text "
        f"({n_prose} prose, {n_comment} with comments); {len(lines)} line(s).",
        file=sys.stderr,
    )
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
